# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: axis.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import vector3d_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='axis.proto',
  package='gazebo.msgs',
  serialized_pb='\n\naxis.proto\x12\x0bgazebo.msgs\x1a\x0evector3d.proto\"\xa5\x01\n\x04\x41xis\x12\"\n\x03xyz\x18\x01 \x02(\x0b\x32\x15.gazebo.msgs.Vector3d\x12\x13\n\x0blimit_lower\x18\x02 \x02(\x01\x12\x13\n\x0blimit_upper\x18\x03 \x02(\x01\x12\x14\n\x0climit_effort\x18\x04 \x02(\x01\x12\x16\n\x0elimit_velocity\x18\x05 \x02(\x01\x12\x0f\n\x07\x64\x61mping\x18\x06 \x02(\x01\x12\x10\n\x08\x66riction\x18\x07 \x02(\x01')




_AXIS = _descriptor.Descriptor(
  name='Axis',
  full_name='gazebo.msgs.Axis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xyz', full_name='gazebo.msgs.Axis.xyz', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit_lower', full_name='gazebo.msgs.Axis.limit_lower', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit_upper', full_name='gazebo.msgs.Axis.limit_upper', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit_effort', full_name='gazebo.msgs.Axis.limit_effort', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit_velocity', full_name='gazebo.msgs.Axis.limit_velocity', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='damping', full_name='gazebo.msgs.Axis.damping', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='friction', full_name='gazebo.msgs.Axis.friction', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=44,
  serialized_end=209,
)

_AXIS.fields_by_name['xyz'].message_type = vector3d_pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['Axis'] = _AXIS

class Axis(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AXIS

  # @@protoc_insertion_point(class_scope:gazebo.msgs.Axis)


# @@protoc_insertion_point(module_scope)
