# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: boxgeom.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import vector3d_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='boxgeom.proto',
  package='gazebo.msgs',
  serialized_pb='\n\rboxgeom.proto\x12\x0bgazebo.msgs\x1a\x0evector3d.proto\".\n\x07\x42oxGeom\x12#\n\x04size\x18\x01 \x02(\x0b\x32\x15.gazebo.msgs.Vector3d')




_BOXGEOM = _descriptor.Descriptor(
  name='BoxGeom',
  full_name='gazebo.msgs.BoxGeom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='gazebo.msgs.BoxGeom.size', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=46,
  serialized_end=92,
)

_BOXGEOM.fields_by_name['size'].message_type = vector3d_pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['BoxGeom'] = _BOXGEOM

class BoxGeom(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BOXGEOM

  # @@protoc_insertion_point(class_scope:gazebo.msgs.BoxGeom)


# @@protoc_insertion_point(module_scope)
