# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_cmd.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import pose_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='camera_cmd.proto',
  package='gazebo.msgs',
  serialized_pb='\n\x10\x63\x61mera_cmd.proto\x12\x0bgazebo.msgs\x1a\npose.proto\"!\n\tCameraCmd\x12\x14\n\x0c\x66ollow_model\x18\x01 \x01(\t')




_CAMERACMD = _descriptor.Descriptor(
  name='CameraCmd',
  full_name='gazebo.msgs.CameraCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='follow_model', full_name='gazebo.msgs.CameraCmd.follow_model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=45,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['CameraCmd'] = _CAMERACMD

class CameraCmd(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CAMERACMD

  # @@protoc_insertion_point(class_scope:gazebo.msgs.CameraCmd)


# @@protoc_insertion_point(module_scope)
