# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contacts.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import contact_pb2
from . import time_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='contacts.proto',
  package='gazebo.msgs',
  serialized_pb=_b('\n\x0e\x63ontacts.proto\x12\x0bgazebo.msgs\x1a\rcontact.proto\x1a\ntime.proto\"R\n\x08\x43ontacts\x12%\n\x07\x63ontact\x18\x01 \x03(\x0b\x32\x14.gazebo.msgs.Contact\x12\x1f\n\x04time\x18\x02 \x02(\x0b\x32\x11.gazebo.msgs.Time')
  ,
  dependencies=[contact_pb2.DESCRIPTOR,time_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONTACTS = _descriptor.Descriptor(
  name='Contacts',
  full_name='gazebo.msgs.Contacts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contact', full_name='gazebo.msgs.Contacts.contact', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='gazebo.msgs.Contacts.time', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=140,
)

_CONTACTS.fields_by_name['contact'].message_type = contact_pb2._CONTACT
_CONTACTS.fields_by_name['time'].message_type = time_pb2._TIME
DESCRIPTOR.message_types_by_name['Contacts'] = _CONTACTS

Contacts = _reflection.GeneratedProtocolMessageType('Contacts', (_message.Message,), dict(
  DESCRIPTOR = _CONTACTS,
  __module__ = 'contacts_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.Contacts)
  ))
_sym_db.RegisterMessage(Contacts)


# @@protoc_insertion_point(module_scope)
