# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contactsensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contactsensor.proto',
  package='gazebo.msgs',
  serialized_pb=_b('\n\x13\x63ontactsensor.proto\x12\x0bgazebo.msgs\"\'\n\rContactSensor\x12\x16\n\x0e\x63ollision_name\x18\x01 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CONTACTSENSOR = _descriptor.Descriptor(
  name='ContactSensor',
  full_name='gazebo.msgs.ContactSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='collision_name', full_name='gazebo.msgs.ContactSensor.collision_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['ContactSensor'] = _CONTACTSENSOR

ContactSensor = _reflection.GeneratedProtocolMessageType('ContactSensor', (_message.Message,), dict(
  DESCRIPTOR = _CONTACTSENSOR,
  __module__ = 'contactsensor_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.ContactSensor)
  ))
_sym_db.RegisterMessage(ContactSensor)


# @@protoc_insertion_point(module_scope)
