# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: factory.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import header_pb2
import pose_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='factory.proto',
  package='gazebo.msgs',
  serialized_pb='\n\rfactory.proto\x12\x0bgazebo.msgs\x1a\x0cheader.proto\x1a\npose.proto\"z\n\x07\x46\x61\x63tory\x12\x0b\n\x03sdf\x18\x01 \x01(\t\x12\x14\n\x0csdf_filename\x18\x02 \x01(\t\x12\x1f\n\x04pose\x18\x03 \x01(\x0b\x32\x11.gazebo.msgs.Pose\x12\x11\n\tedit_name\x18\x04 \x01(\t\x12\x18\n\x10\x63lone_model_name\x18\x05 \x01(\t')




_FACTORY = _descriptor.Descriptor(
  name='Factory',
  full_name='gazebo.msgs.Factory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sdf', full_name='gazebo.msgs.Factory.sdf', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sdf_filename', full_name='gazebo.msgs.Factory.sdf_filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='gazebo.msgs.Factory.pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='edit_name', full_name='gazebo.msgs.Factory.edit_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clone_model_name', full_name='gazebo.msgs.Factory.clone_model_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=56,
  serialized_end=178,
)

_FACTORY.fields_by_name['pose'].message_type = pose_pb2._POSE
DESCRIPTOR.message_types_by_name['Factory'] = _FACTORY

class Factory(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FACTORY

  # @@protoc_insertion_point(class_scope:gazebo.msgs.Factory)


# @@protoc_insertion_point(module_scope)
