# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: friction.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import vector3d_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='friction.proto',
  package='gazebo.msgs',
  serialized_pb='\n\x0e\x66riction.proto\x12\x0bgazebo.msgs\x1a\x0evector3d.proto\"g\n\x08\x46riction\x12\n\n\x02mu\x18\x01 \x01(\x01\x12\x0b\n\x03mu2\x18\x02 \x01(\x01\x12$\n\x05\x66\x64ir1\x18\x03 \x01(\x0b\x32\x15.gazebo.msgs.Vector3d\x12\r\n\x05slip1\x18\x04 \x01(\x01\x12\r\n\x05slip2\x18\x05 \x01(\x01')




_FRICTION = _descriptor.Descriptor(
  name='Friction',
  full_name='gazebo.msgs.Friction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mu', full_name='gazebo.msgs.Friction.mu', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mu2', full_name='gazebo.msgs.Friction.mu2', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fdir1', full_name='gazebo.msgs.Friction.fdir1', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slip1', full_name='gazebo.msgs.Friction.slip1', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slip2', full_name='gazebo.msgs.Friction.slip2', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=47,
  serialized_end=150,
)

_FRICTION.fields_by_name['fdir1'].message_type = vector3d_pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['Friction'] = _FRICTION

class Friction(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FRICTION

  # @@protoc_insertion_point(class_scope:gazebo.msgs.Friction)


# @@protoc_insertion_point(module_scope)
