# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import gui_camera_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gui.proto',
  package='gazebo.msgs',
  serialized_pb=_b('\n\tgui.proto\x12\x0bgazebo.msgs\x1a\x10gui_camera.proto\"A\n\x03GUI\x12\x12\n\nfullscreen\x18\x01 \x01(\x08\x12&\n\x06\x63\x61mera\x18\x02 \x01(\x0b\x32\x16.gazebo.msgs.GUICamera')
  ,
  dependencies=[gui_camera_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GUI = _descriptor.Descriptor(
  name='GUI',
  full_name='gazebo.msgs.GUI',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fullscreen', full_name='gazebo.msgs.GUI.fullscreen', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='camera', full_name='gazebo.msgs.GUI.camera', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=109,
)

_GUI.fields_by_name['camera'].message_type = gui_camera_pb2._GUICAMERA
DESCRIPTOR.message_types_by_name['GUI'] = _GUI

GUI = _reflection.GeneratedProtocolMessageType('GUI', (_message.Message,), dict(
  DESCRIPTOR = _GUI,
  __module__ = 'gui_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.GUI)
  ))
_sym_db.RegisterMessage(GUI)


# @@protoc_insertion_point(module_scope)
