# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui_camera.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import pose_pb2
import track_visual_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gui_camera.proto',
  package='gazebo.msgs',
  serialized_pb='\n\x10gui_camera.proto\x12\x0bgazebo.msgs\x1a\npose.proto\x1a\x12track_visual.proto\"|\n\tGUICamera\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x17\n\x0fview_controller\x18\x02 \x01(\t\x12\x1f\n\x04pose\x18\x03 \x01(\x0b\x32\x11.gazebo.msgs.Pose\x12\'\n\x05track\x18\x04 \x01(\x0b\x32\x18.gazebo.msgs.TrackVisual')




_GUICAMERA = _descriptor.Descriptor(
  name='GUICamera',
  full_name='gazebo.msgs.GUICamera',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gazebo.msgs.GUICamera.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='view_controller', full_name='gazebo.msgs.GUICamera.view_controller', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='gazebo.msgs.GUICamera.pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='track', full_name='gazebo.msgs.GUICamera.track', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=65,
  serialized_end=189,
)

_GUICAMERA.fields_by_name['pose'].message_type = pose_pb2._POSE
_GUICAMERA.fields_by_name['track'].message_type = track_visual_pb2._TRACKVISUAL
DESCRIPTOR.message_types_by_name['GUICamera'] = _GUICAMERA

class GUICamera(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GUICAMERA

  # @@protoc_insertion_point(class_scope:gazebo.msgs.GUICamera)


# @@protoc_insertion_point(module_scope)
