# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gui_overlay_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gui_overlay_config.proto',
  package='gazebo.msgs',
  serialized_pb=_b('\n\x18gui_overlay_config.proto\x12\x0bgazebo.msgs\"+\n\x10GUIOverlayConfig\x12\x17\n\x0flayout_filename\x18\x01 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GUIOVERLAYCONFIG = _descriptor.Descriptor(
  name='GUIOverlayConfig',
  full_name='gazebo.msgs.GUIOverlayConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layout_filename', full_name='gazebo.msgs.GUIOverlayConfig.layout_filename', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['GUIOverlayConfig'] = _GUIOVERLAYCONFIG

GUIOverlayConfig = _reflection.GeneratedProtocolMessageType('GUIOverlayConfig', (_message.Message,), dict(
  DESCRIPTOR = _GUIOVERLAYCONFIG,
  __module__ = 'gui_overlay_config_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.GUIOverlayConfig)
  ))
_sym_db.RegisterMessage(GUIOverlayConfig)


# @@protoc_insertion_point(module_scope)
