# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='gz_string_v.proto',
  package='gazebo.msgs',
  serialized_pb='\n\x11gz_string_v.proto\x12\x0bgazebo.msgs\"\x1a\n\nGzString_V\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t')




_GZSTRING_V = descriptor.Descriptor(
  name='GzString_V',
  full_name='gazebo.msgs.GzString_V',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data', full_name='gazebo.msgs.GzString_V.data', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=60,
)

DESCRIPTOR.message_types_by_name['GzString_V'] = _GZSTRING_V

class GzString_V(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GZSTRING_V
  
  # @@protoc_insertion_point(class_scope:gazebo.msgs.GzString_V)

# @@protoc_insertion_point(module_scope)
