# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imu.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import time_pb2
from . import vector3d_pb2
from . import quaternion_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='imu.proto',
  package='gazebo.msgs',
  serialized_pb=_b('\n\timu.proto\x12\x0bgazebo.msgs\x1a\ntime.proto\x1a\x0evector3d.proto\x1a\x10quaternion.proto\"\xcf\x01\n\x03IMU\x12 \n\x05stamp\x18\x01 \x02(\x0b\x32\x11.gazebo.msgs.Time\x12\x13\n\x0b\x65ntity_name\x18\x02 \x02(\t\x12,\n\x0borientation\x18\x03 \x02(\x0b\x32\x17.gazebo.msgs.Quaternion\x12/\n\x10\x61ngular_velocity\x18\x04 \x02(\x0b\x32\x15.gazebo.msgs.Vector3d\x12\x32\n\x13linear_acceleration\x18\x05 \x02(\x0b\x32\x15.gazebo.msgs.Vector3d')
  ,
  dependencies=[time_pb2.DESCRIPTOR,vector3d_pb2.DESCRIPTOR,quaternion_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IMU = _descriptor.Descriptor(
  name='IMU',
  full_name='gazebo.msgs.IMU',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stamp', full_name='gazebo.msgs.IMU.stamp', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entity_name', full_name='gazebo.msgs.IMU.entity_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='gazebo.msgs.IMU.orientation', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angular_velocity', full_name='gazebo.msgs.IMU.angular_velocity', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linear_acceleration', full_name='gazebo.msgs.IMU.linear_acceleration', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=280,
)

_IMU.fields_by_name['stamp'].message_type = time_pb2._TIME
_IMU.fields_by_name['orientation'].message_type = quaternion_pb2._QUATERNION
_IMU.fields_by_name['angular_velocity'].message_type = vector3d_pb2._VECTOR3D
_IMU.fields_by_name['linear_acceleration'].message_type = vector3d_pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['IMU'] = _IMU

IMU = _reflection.GeneratedProtocolMessageType('IMU', (_message.Message,), dict(
  DESCRIPTOR = _IMU,
  __module__ = 'imu_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.IMU)
  ))
_sym_db.RegisterMessage(IMU)


# @@protoc_insertion_point(module_scope)
