# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: laserscan_stamped.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import time_pb2
import laserscan_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='laserscan_stamped.proto',
  package='gazebo.msgs',
  serialized_pb='\n\x17laserscan_stamped.proto\x12\x0bgazebo.msgs\x1a\ntime.proto\x1a\x0flaserscan.proto\"Y\n\x10LaserScanStamped\x12\x1f\n\x04time\x18\x01 \x02(\x0b\x32\x11.gazebo.msgs.Time\x12$\n\x04scan\x18\x02 \x02(\x0b\x32\x16.gazebo.msgs.LaserScan')




_LASERSCANSTAMPED = _descriptor.Descriptor(
  name='LaserScanStamped',
  full_name='gazebo.msgs.LaserScanStamped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='gazebo.msgs.LaserScanStamped.time', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scan', full_name='gazebo.msgs.LaserScanStamped.scan', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=69,
  serialized_end=158,
)

_LASERSCANSTAMPED.fields_by_name['time'].message_type = time_pb2._TIME
_LASERSCANSTAMPED.fields_by_name['scan'].message_type = laserscan_pb2._LASERSCAN
DESCRIPTOR.message_types_by_name['LaserScanStamped'] = _LASERSCANSTAMPED

class LaserScanStamped(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LASERSCANSTAMPED

  # @@protoc_insertion_point(class_scope:gazebo.msgs.LaserScanStamped)


# @@protoc_insertion_point(module_scope)
