# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: light.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import header_pb2
import pose_pb2
import vector3d_pb2
import color_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='light.proto',
  package='gazebo.msgs',
  serialized_pb='\n\x0blight.proto\x12\x0bgazebo.msgs\x1a\x0cheader.proto\x1a\npose.proto\x1a\x0evector3d.proto\x1a\x0b\x63olor.proto\"\xd2\x03\n\x05Light\x12\x0c\n\x04name\x18\x01 \x02(\t\x12*\n\x04type\x18\x02 \x01(\x0e\x32\x1c.gazebo.msgs.Light.LightType\x12\x1f\n\x04pose\x18\x03 \x01(\x0b\x32\x11.gazebo.msgs.Pose\x12#\n\x07\x64iffuse\x18\x04 \x01(\x0b\x32\x12.gazebo.msgs.Color\x12$\n\x08specular\x18\x05 \x01(\x0b\x32\x12.gazebo.msgs.Color\x12\x1c\n\x14\x61ttenuation_constant\x18\x06 \x01(\x02\x12\x1a\n\x12\x61ttenuation_linear\x18\x07 \x01(\x02\x12\x1d\n\x15\x61ttenuation_quadratic\x18\x08 \x01(\x02\x12(\n\tdirection\x18\t \x01(\x0b\x32\x15.gazebo.msgs.Vector3d\x12\r\n\x05range\x18\n \x01(\x02\x12\x14\n\x0c\x63\x61st_shadows\x18\x0b \x01(\x08\x12\x18\n\x10spot_inner_angle\x18\x0c \x01(\x02\x12\x18\n\x10spot_outer_angle\x18\r \x01(\x02\x12\x14\n\x0cspot_falloff\x18\x0e \x01(\x02\"1\n\tLightType\x12\t\n\x05POINT\x10\x01\x12\x08\n\x04SPOT\x10\x02\x12\x0f\n\x0b\x44IRECTIONAL\x10\x03')



_LIGHT_LIGHTTYPE = _descriptor.EnumDescriptor(
  name='LightType',
  full_name='gazebo.msgs.Light.LightType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='POINT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPOT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DIRECTIONAL', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=501,
  serialized_end=550,
)


_LIGHT = _descriptor.Descriptor(
  name='Light',
  full_name='gazebo.msgs.Light',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gazebo.msgs.Light.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='gazebo.msgs.Light.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose', full_name='gazebo.msgs.Light.pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diffuse', full_name='gazebo.msgs.Light.diffuse', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='specular', full_name='gazebo.msgs.Light.specular', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attenuation_constant', full_name='gazebo.msgs.Light.attenuation_constant', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attenuation_linear', full_name='gazebo.msgs.Light.attenuation_linear', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attenuation_quadratic', full_name='gazebo.msgs.Light.attenuation_quadratic', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='direction', full_name='gazebo.msgs.Light.direction', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='range', full_name='gazebo.msgs.Light.range', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cast_shadows', full_name='gazebo.msgs.Light.cast_shadows', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spot_inner_angle', full_name='gazebo.msgs.Light.spot_inner_angle', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spot_outer_angle', full_name='gazebo.msgs.Light.spot_outer_angle', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spot_falloff', full_name='gazebo.msgs.Light.spot_falloff', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LIGHT_LIGHTTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=84,
  serialized_end=550,
)

_LIGHT.fields_by_name['type'].enum_type = _LIGHT_LIGHTTYPE
_LIGHT.fields_by_name['pose'].message_type = pose_pb2._POSE
_LIGHT.fields_by_name['diffuse'].message_type = color_pb2._COLOR
_LIGHT.fields_by_name['specular'].message_type = color_pb2._COLOR
_LIGHT.fields_by_name['direction'].message_type = vector3d_pb2._VECTOR3D
_LIGHT_LIGHTTYPE.containing_type = _LIGHT;
DESCRIPTOR.message_types_by_name['Light'] = _LIGHT

class Light(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LIGHT

  # @@protoc_insertion_point(class_scope:gazebo.msgs.Light)


# @@protoc_insertion_point(module_scope)
