# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import color_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='material.proto',
  package='gazebo.msgs',
  serialized_pb='\n\x0ematerial.proto\x12\x0bgazebo.msgs\x1a\x0b\x63olor.proto\"\x9e\x03\n\x08Material\x12,\n\x06script\x18\x01 \x01(\x0b\x32\x1c.gazebo.msgs.Material.Script\x12\x35\n\x0bshader_type\x18\x02 \x01(\x0e\x32 .gazebo.msgs.Material.ShaderType\x12\x12\n\nnormal_map\x18\x03 \x01(\t\x12#\n\x07\x61mbient\x18\x04 \x01(\x0b\x32\x12.gazebo.msgs.Color\x12#\n\x07\x64iffuse\x18\x05 \x01(\x0b\x32\x12.gazebo.msgs.Color\x12$\n\x08specular\x18\x06 \x01(\x0b\x32\x12.gazebo.msgs.Color\x12$\n\x08\x65missive\x18\x07 \x01(\x0b\x32\x12.gazebo.msgs.Color\x1a#\n\x06Script\x12\x0b\n\x03uri\x18\x01 \x03(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\"^\n\nShaderType\x12\n\n\x06VERTEX\x10\x01\x12\t\n\x05PIXEL\x10\x02\x12\x1b\n\x17NORMAL_MAP_OBJECT_SPACE\x10\x03\x12\x1c\n\x18NORMAL_MAP_TANGENT_SPACE\x10\x04')



_MATERIAL_SHADERTYPE = descriptor.EnumDescriptor(
  name='ShaderType',
  full_name='gazebo.msgs.Material.ShaderType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='VERTEX', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PIXEL', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NORMAL_MAP_OBJECT_SPACE', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NORMAL_MAP_TANGENT_SPACE', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=365,
  serialized_end=459,
)


_MATERIAL_SCRIPT = descriptor.Descriptor(
  name='Script',
  full_name='gazebo.msgs.Material.Script',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='uri', full_name='gazebo.msgs.Material.Script.uri', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='gazebo.msgs.Material.Script.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=328,
  serialized_end=363,
)

_MATERIAL = descriptor.Descriptor(
  name='Material',
  full_name='gazebo.msgs.Material',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='script', full_name='gazebo.msgs.Material.script', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shader_type', full_name='gazebo.msgs.Material.shader_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='normal_map', full_name='gazebo.msgs.Material.normal_map', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='ambient', full_name='gazebo.msgs.Material.ambient', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='diffuse', full_name='gazebo.msgs.Material.diffuse', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='specular', full_name='gazebo.msgs.Material.specular', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='emissive', full_name='gazebo.msgs.Material.emissive', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MATERIAL_SCRIPT, ],
  enum_types=[
    _MATERIAL_SHADERTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=45,
  serialized_end=459,
)

_MATERIAL_SCRIPT.containing_type = _MATERIAL;
_MATERIAL.fields_by_name['script'].message_type = _MATERIAL_SCRIPT
_MATERIAL.fields_by_name['shader_type'].enum_type = _MATERIAL_SHADERTYPE
_MATERIAL.fields_by_name['ambient'].message_type = color_pb2._COLOR
_MATERIAL.fields_by_name['diffuse'].message_type = color_pb2._COLOR
_MATERIAL.fields_by_name['specular'].message_type = color_pb2._COLOR
_MATERIAL.fields_by_name['emissive'].message_type = color_pb2._COLOR
_MATERIAL_SHADERTYPE.containing_type = _MATERIAL;
DESCRIPTOR.message_types_by_name['Material'] = _MATERIAL

class Material(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Script(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _MATERIAL_SCRIPT
    
    # @@protoc_insertion_point(class_scope:gazebo.msgs.Material.Script)
  DESCRIPTOR = _MATERIAL
  
  # @@protoc_insertion_point(class_scope:gazebo.msgs.Material)

# @@protoc_insertion_point(module_scope)
