# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_v.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import model_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='model_v.proto',
  package='gazebo.msgs',
  serialized_pb='\n\rmodel_v.proto\x12\x0bgazebo.msgs\x1a\x0bmodel.proto\"-\n\x07Model_V\x12\"\n\x06models\x18\x02 \x03(\x0b\x32\x12.gazebo.msgs.Model')




_MODEL_V = _descriptor.Descriptor(
  name='Model_V',
  full_name='gazebo.msgs.Model_V',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='models', full_name='gazebo.msgs.Model_V.models', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=43,
  serialized_end=88,
)

_MODEL_V.fields_by_name['models'].message_type = model_pb2._MODEL
DESCRIPTOR.message_types_by_name['Model_V'] = _MODEL_V

class Model_V(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MODEL_V

  # @@protoc_insertion_point(class_scope:gazebo.msgs.Model_V)


# @@protoc_insertion_point(module_scope)
