# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pointcloud.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import vector3d_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pointcloud.proto',
  package='gazebo.msgs',
  serialized_pb='\n\x10pointcloud.proto\x12\x0bgazebo.msgs\x1a\x0evector3d.proto\"3\n\nPointCloud\x12%\n\x06points\x18\x01 \x03(\x0b\x32\x15.gazebo.msgs.Vector3d')




_POINTCLOUD = _descriptor.Descriptor(
  name='PointCloud',
  full_name='gazebo.msgs.PointCloud',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='gazebo.msgs.PointCloud.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=49,
  serialized_end=100,
)

_POINTCLOUD.fields_by_name['points'].message_type = vector3d_pb2._VECTOR3D
DESCRIPTOR.message_types_by_name['PointCloud'] = _POINTCLOUD

class PointCloud(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POINTCLOUD

  # @@protoc_insertion_point(class_scope:gazebo.msgs.PointCloud)


# @@protoc_insertion_point(module_scope)
