# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import pose_pb2
import time_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='pose_animation.proto',
  package='gazebo.msgs',
  serialized_pb='\n\x14pose_animation.proto\x12\x0bgazebo.msgs\x1a\npose.proto\x1a\ntime.proto\"w\n\rPoseAnimation\x12\x12\n\nmodel_name\x18\x01 \x02(\t\x12\x10\n\x08model_id\x18\x02 \x01(\r\x12\x1f\n\x04pose\x18\x03 \x03(\x0b\x32\x11.gazebo.msgs.Pose\x12\x1f\n\x04time\x18\x04 \x03(\x0b\x32\x11.gazebo.msgs.Time')




_POSEANIMATION = descriptor.Descriptor(
  name='PoseAnimation',
  full_name='gazebo.msgs.PoseAnimation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='model_name', full_name='gazebo.msgs.PoseAnimation.model_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='model_id', full_name='gazebo.msgs.PoseAnimation.model_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pose', full_name='gazebo.msgs.PoseAnimation.pose', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='time', full_name='gazebo.msgs.PoseAnimation.time', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=61,
  serialized_end=180,
)

_POSEANIMATION.fields_by_name['pose'].message_type = pose_pb2._POSE
_POSEANIMATION.fields_by_name['time'].message_type = time_pb2._TIME
DESCRIPTOR.message_types_by_name['PoseAnimation'] = _POSEANIMATION

class PoseAnimation(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POSEANIMATION
  
  # @@protoc_insertion_point(class_scope:gazebo.msgs.PoseAnimation)

# @@protoc_insertion_point(module_scope)
