# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: propagation_grid.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import propagation_particle_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='propagation_grid.proto',
  package='gazebo.msgs',
  serialized_pb='\n\x16propagation_grid.proto\x12\x0bgazebo.msgs\x1a\x1apropagation_particle.proto\"E\n\x0fPropagationGrid\x12\x32\n\x08particle\x18\x01 \x03(\x0b\x32 .gazebo.msgs.PropagationParticle')




_PROPAGATIONGRID = _descriptor.Descriptor(
  name='PropagationGrid',
  full_name='gazebo.msgs.PropagationGrid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='particle', full_name='gazebo.msgs.PropagationGrid.particle', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=67,
  serialized_end=136,
)

_PROPAGATIONGRID.fields_by_name['particle'].message_type = propagation_particle_pb2._PROPAGATIONPARTICLE
DESCRIPTOR.message_types_by_name['PropagationGrid'] = _PROPAGATIONGRID

class PropagationGrid(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROPAGATIONGRID

  # @@protoc_insertion_point(class_scope:gazebo.msgs.PropagationGrid)


# @@protoc_insertion_point(module_scope)
