# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scene.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import header_pb2
import color_pb2
import fog_pb2
import sky_pb2
import shadows_pb2
import visual_pb2
import pose_pb2
import light_pb2
import joint_pb2
import model_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scene.proto',
  package='gazebo.msgs',
  serialized_pb='\n\x0bscene.proto\x12\x0bgazebo.msgs\x1a\x0cheader.proto\x1a\x0b\x63olor.proto\x1a\tfog.proto\x1a\tsky.proto\x1a\rshadows.proto\x1a\x0cvisual.proto\x1a\npose.proto\x1a\x0blight.proto\x1a\x0bjoint.proto\x1a\x0bmodel.proto\"\xae\x02\n\x05Scene\x12\x0c\n\x04name\x18\x01 \x02(\t\x12#\n\x07\x61mbient\x18\x02 \x01(\x0b\x32\x12.gazebo.msgs.Color\x12&\n\nbackground\x18\x03 \x01(\x0b\x32\x12.gazebo.msgs.Color\x12\x1d\n\x03sky\x18\x04 \x01(\x0b\x32\x10.gazebo.msgs.Sky\x12\x15\n\x07shadows\x18\x05 \x01(\x08:\x04true\x12\x1d\n\x03\x66og\x18\x06 \x01(\x0b\x32\x10.gazebo.msgs.Fog\x12\x0c\n\x04grid\x18\x07 \x01(\x08\x12!\n\x05model\x18\x08 \x03(\x0b\x32\x12.gazebo.msgs.Model\x12!\n\x05light\x18\t \x03(\x0b\x32\x12.gazebo.msgs.Light\x12!\n\x05joint\x18\n \x03(\x0b\x32\x12.gazebo.msgs.Joint')




_SCENE = _descriptor.Descriptor(
  name='Scene',
  full_name='gazebo.msgs.Scene',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gazebo.msgs.Scene.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ambient', full_name='gazebo.msgs.Scene.ambient', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='background', full_name='gazebo.msgs.Scene.background', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sky', full_name='gazebo.msgs.Scene.sky', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shadows', full_name='gazebo.msgs.Scene.shadows', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fog', full_name='gazebo.msgs.Scene.fog', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='grid', full_name='gazebo.msgs.Scene.grid', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model', full_name='gazebo.msgs.Scene.model', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='light', full_name='gazebo.msgs.Scene.light', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='joint', full_name='gazebo.msgs.Scene.joint', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=158,
  serialized_end=460,
)

_SCENE.fields_by_name['ambient'].message_type = color_pb2._COLOR
_SCENE.fields_by_name['background'].message_type = color_pb2._COLOR
_SCENE.fields_by_name['sky'].message_type = sky_pb2._SKY
_SCENE.fields_by_name['fog'].message_type = fog_pb2._FOG
_SCENE.fields_by_name['model'].message_type = model_pb2._MODEL
_SCENE.fields_by_name['light'].message_type = light_pb2._LIGHT
_SCENE.fields_by_name['joint'].message_type = joint_pb2._JOINT
DESCRIPTOR.message_types_by_name['Scene'] = _SCENE

class Scene(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCENE

  # @@protoc_insertion_point(class_scope:gazebo.msgs.Scene)


# @@protoc_insertion_point(module_scope)
