# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sky.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import color_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sky.proto',
  package='gazebo.msgs',
  serialized_pb='\n\tsky.proto\x12\x0bgazebo.msgs\x1a\x0b\x63olor.proto\"\xb6\x01\n\x03Sky\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x0f\n\x07sunrise\x18\x02 \x01(\x01\x12\x0e\n\x06sunset\x18\x03 \x01(\x01\x12\x12\n\nwind_speed\x18\x04 \x01(\x01\x12\x16\n\x0ewind_direction\x18\x05 \x01(\x01\x12)\n\rcloud_ambient\x18\x06 \x01(\x0b\x32\x12.gazebo.msgs.Color\x12\x10\n\x08humidity\x18\x07 \x01(\x01\x12\x17\n\x0fmean_cloud_size\x18\x08 \x01(\x01')




_SKY = _descriptor.Descriptor(
  name='Sky',
  full_name='gazebo.msgs.Sky',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='gazebo.msgs.Sky.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sunrise', full_name='gazebo.msgs.Sky.sunrise', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sunset', full_name='gazebo.msgs.Sky.sunset', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wind_speed', full_name='gazebo.msgs.Sky.wind_speed', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wind_direction', full_name='gazebo.msgs.Sky.wind_direction', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cloud_ambient', full_name='gazebo.msgs.Sky.cloud_ambient', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='gazebo.msgs.Sky.humidity', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean_cloud_size', full_name='gazebo.msgs.Sky.mean_cloud_size', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=222,
)

_SKY.fields_by_name['cloud_ambient'].message_type = color_pb2._COLOR
DESCRIPTOR.message_types_by_name['Sky'] = _SKY

class Sky(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SKY

  # @@protoc_insertion_point(class_scope:gazebo.msgs.Sky)


# @@protoc_insertion_point(module_scope)
