# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spheregeom.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spheregeom.proto',
  package='gazebo.msgs',
  serialized_pb='\n\x10spheregeom.proto\x12\x0bgazebo.msgs\"\x1c\n\nSphereGeom\x12\x0e\n\x06radius\x18\x01 \x02(\x01')




_SPHEREGEOM = _descriptor.Descriptor(
  name='SphereGeom',
  full_name='gazebo.msgs.SphereGeom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='radius', full_name='gazebo.msgs.SphereGeom.radius', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['SphereGeom'] = _SPHEREGEOM

class SphereGeom(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPHEREGEOM

  # @@protoc_insertion_point(class_scope:gazebo.msgs.SphereGeom)


# @@protoc_insertion_point(module_scope)
