# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import header_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='gazebo.msgs',
  serialized_pb='\n\ntest.proto\x12\x0bgazebo.msgs\x1a\x0cheader.proto\"+\n\x04Test\x12#\n\x06header\x18\x01 \x02(\x0b\x32\x13.gazebo.msgs.Header')




_TEST = _descriptor.Descriptor(
  name='Test',
  full_name='gazebo.msgs.Test',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='gazebo.msgs.Test.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=41,
  serialized_end=84,
)

_TEST.fields_by_name['header'].message_type = header_pb2._HEADER
DESCRIPTOR.message_types_by_name['Test'] = _TEST

class Test(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TEST

  # @@protoc_insertion_point(class_scope:gazebo.msgs.Test)


# @@protoc_insertion_point(module_scope)
