# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wireless_node.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wireless_node.proto',
  package='gazebo.msgs',
  serialized_pb=_b('\n\x13wireless_node.proto\x12\x0bgazebo.msgs\"F\n\x0cWirelessNode\x12\r\n\x05\x65ssid\x18\x01 \x02(\t\x12\x11\n\tfrequency\x18\x02 \x02(\x01\x12\x14\n\x0csignal_level\x18\x03 \x02(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_WIRELESSNODE = _descriptor.Descriptor(
  name='WirelessNode',
  full_name='gazebo.msgs.WirelessNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='essid', full_name='gazebo.msgs.WirelessNode.essid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frequency', full_name='gazebo.msgs.WirelessNode.frequency', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signal_level', full_name='gazebo.msgs.WirelessNode.signal_level', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['WirelessNode'] = _WIRELESSNODE

WirelessNode = _reflection.GeneratedProtocolMessageType('WirelessNode', (_message.Message,), dict(
  DESCRIPTOR = _WIRELESSNODE,
  __module__ = 'wireless_node_pb2'
  # @@protoc_insertion_point(class_scope:gazebo.msgs.WirelessNode)
  ))
_sym_db.RegisterMessage(WirelessNode)


# @@protoc_insertion_point(module_scope)
