# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='wireless_node.proto',
  package='gazebo.msgs',
  serialized_pb='\n\x13wireless_node.proto\x12\x0bgazebo.msgs\"F\n\x0cWirelessNode\x12\r\n\x05\x65ssid\x18\x01 \x02(\t\x12\x11\n\tfrequency\x18\x02 \x02(\x01\x12\x14\n\x0csignal_level\x18\x03 \x02(\x01')




_WIRELESSNODE = descriptor.Descriptor(
  name='WirelessNode',
  full_name='gazebo.msgs.WirelessNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='essid', full_name='gazebo.msgs.WirelessNode.essid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='frequency', full_name='gazebo.msgs.WirelessNode.frequency', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='signal_level', full_name='gazebo.msgs.WirelessNode.signal_level', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['WirelessNode'] = _WIRELESSNODE

class WirelessNode(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WIRELESSNODE
  
  # @@protoc_insertion_point(class_scope:gazebo.msgs.WirelessNode)

# @@protoc_insertion_point(module_scope)
